"""empty message

Revision ID: 03d66a849ce1
Revises: 50f9b43209bd
Create Date: 2020-05-14 00:35:06.140593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d66a849ce1'
down_revision = '50f9b43209bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcodes',
    sa.Column('barcode_id', sa.Integer(), nullable=False),
    sa.Column('barcode_code', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('barcode_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barcodes')
    # ### end Alembic commands ###
