"""empty message

Revision ID: 3d30e4d6facc
Revises: 1bae017a8611
Create Date: 2020-05-20 07:56:49.525504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d30e4d6facc'
down_revision = '1bae017a8611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_password',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_password',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
