"""empty message

Revision ID: 45892c6afbcb
Revises: b3ae32b28f07
Create Date: 2020-05-14 01:08:36.487637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45892c6afbcb'
down_revision = 'b3ae32b28f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('prod_id', sa.Integer(), nullable=False),
    sa.Column('prod_name', sa.String(length=45), nullable=False),
    sa.Column('prod_info', sa.String(length=300), nullable=True),
    sa.Column('prod_brand', sa.String(length=45), nullable=True),
    sa.Column('prod_image_id', sa.Integer(), nullable=True),
    sa.Column('prod_barcode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prod_barcode_id'], ['barcodes.barcode_id'], ),
    sa.ForeignKeyConstraint(['prod_image_id'], ['images.image_id'], ),
    sa.PrimaryKeyConstraint('prod_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
