"""empty message

Revision ID: 50f9b43209bd
Revises: da58dae1b1c1
Create Date: 2020-05-14 00:29:21.882072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50f9b43209bd'
down_revision = 'da58dae1b1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'language_lang',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'language_lang',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
