"""empty message

Revision ID: ca37bb863fd9
Revises: ec12c5e11cfa
Create Date: 2020-05-26 00:36:45.060291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca37bb863fd9'
down_revision = 'ec12c5e11cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_role',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'user_roles', ['user_role'], ['user_role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'user_role',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
