"""empty message

Revision ID: d259fc18aa10
Revises: 
Create Date: 2020-05-13 23:42:20.716761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd259fc18aa10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('language_lang', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('language_lang')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=32), nullable=False),
    sa.Column('user_create_datetime', sa.DateTime(timezone=3), nullable=False),
    sa.Column('user_first_name', sa.String(length=45), nullable=True),
    sa.Column('user_last_name', sa.String(length=45), nullable=True),
    sa.Column('user_address', sa.String(length=255), nullable=False),
    sa.Column('user_country', sa.String(length=45), nullable=True),
    sa.Column('user_city', sa.String(length=45), nullable=True),
    sa.Column('user_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_language_id'], ['languages.language_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
